---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oidc
  namespace: penpot
spec:
  encryptedData:
    client-id: AgBpuijmFnhbcgLEhxeoeemrHYsSJolF9MzwiNThX+Ysomk/53ae0vhv6i0haxU3D1EJJzhh3HZLmp2LDef4RauPgSNjl+e8QUExjnNXE/xyioUBG1HfIi3J0m4O1qssexW+0TpXSzDW9TDZI8kRjV9VhJUwXgDoydlOOi0gjyZyBcqBS5TYsl/qCmE47YB7y8csExW1kxulgOKiUf7FJkvBNBbQajgpcccm9/YvVrdqjU5Vz0YYheB6rvTyRJ1tSSvT3qdv8p7HQsBQT9gFUEEuxSIVGBERMMIdprHbRr6a3nYTwwCAN97usPjQ1WTrvE6GgNP103vWYx+TxNeDM+Gq8syKOaqxnAlukzlPCLV/+iPhayckw2aiACMaIkKNb6mNbz+Ot5DlrmxDJMX9ou/23lzQ3kJk8UrV7OIcciqIe/VbcJ24yn9dy0u4SHBke8XTDkE4HwXMDGqKKE4Srgxtrh0SVI9onsUhP3VbpZo1EciM/vdWQQ0RJIoxTonB/IIOuMIBLMfMA6wPCUbo7a1vTsT0KADx76KgNCFhu/mTN4LQ9IHvAoMo5Et0kwxte4VWKOgoaqIwFd7oFchoyDWDaL8ej4tNNJ1VUTWFSNelnPGFPjfYmlLbNEpB+oahrZ4/gr3CmD7q76omQdnZ+JzTXsDZBpCRQcgxIEteiDPyh8XoGBzfDQ8Wm6pyO6jUgnyGhHtOkP5lddqpk0oDNlGD98hfC+vLPRAci8OUbaBRY9xjgajyQcLv
    client-secret: AgCYK0LpeJr7CMHMWCNYWRDn9G3rVp+hiPVpRDJulWy+xpnvKVoWllflXT8GDsPrKHVpzrVFWkWc6WcBTUxEguAmN7B0lfvUMvJzoQEEVt8jk2EYtuGjPKu7VvMxTqbXNDSVWoh5y1VPKBHaYvPtPfneLIef3HVvPoG/iVONPLZmYyWXDT7OKsoNtZ6pxRFxKhsaLiRbBA/agzm7OVu8uRTrcvxUMP3FVgvYKS5vMbdszGfpA31JNKTr978RKY1A7p8oS+g2oSTGf7PlLo+5bgOpmkQ5s8paNbuKLh6dt+uypbWRjmbEg+8jM7ZR+2fPKWQR/bw09Izk77Yjb2rsKj/47ILYj+akpfwfi8VvPjXlT2Zv3r4P3IZTTOGAS86PCHUa4cHfNkQia9IOIqfH1cTfOFS6PhRkGutzYiByMr+C9JuUUscHSY8WXKYg6vuvtZ/eNRCvSF3UKUQefqcLRk3dbIe0So5blRgondWTJMdQcnXUwlxwcE5BICA1L6elGFN33BTevsA8hl4JlOkfrA2Q1+N4C3hdgTWzZthzh18M4izNUFllmua8fPf8uAn7KA2CeZCIIF6ygkhEV49WdOn09EW8T9QqFpOHA+bYy6sShKGPqm0TQOo8+1hVN/JlPnbZkmOJNkuuWwoXo6Iz70fStjPzQ1OOdVJtrOhRmXlorsMpRTLELwkSUoVNlh9PPnA2izYkvseIKS2ki9543u4yRtf9sieX1UpeL1nnA0VZencYiNQzds5C8+XfrFin6DJXnbjGVIDabkho+v1AHEGmK72XwV5Zc4Fx/1dcS3AYQK04yIwI+YVxDlxJKG2IbDsI4Cdsir2suLBhZNElvLQj2i7SuZunlhDohEiaFvzNXQ==
  template:
    metadata:
      creationTimestamp: null
      name: oidc
      namespace: penpot
