apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-web
spec:
  destination:
    namespace: app-web
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://github.com/openlab-aux/openlab-app.git"
    targetRevision: "feat/k8s-manifests"
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
