apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: "default"
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: 9.3.5
    chart: argo-cd
    helm:
      values: |
        installCRDs: True

        configs:
          params:
            server.insecure: false

          cm:
            create: false

          rbac:
            policy.csv: |
              g, ArgoCD Admins, role:admin

        dex:
          enabled: false

        redis:
          enabled: false

        server:
          ingress:
            enabled: true
            https: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: le-prod
            hostname: argocd.lab.weltraumpflege.org
            tls: true
        redis-ha:
          enabled: false

        redis:
          enabled: true

        crds:
          install: false
          keep: false