apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: "default"
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.13.3
    chart: cert-manager