apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  project: "default"
  destination:
    namespace: cnpg-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://cloudnative-pg.github.io/charts"
    targetRevision: 0.23.2
    chart: cloudnative-pg