apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cryptpad
spec:
  project: "default"
  destination:
    namespace: cryptpad
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "ghcr.io/cryptpad/helm"
      chart: cryptpad
      targetRevision: 0.0.21
      helm:
        values: |
          persistence:
            cryptpad:
              blob:
                size: 5Gi
              block:
                size: 5Gi
              data:
                size: 5Gi
              datastore:
                size: 5Gi  
          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: le-prod
            hosts:
            - host: ola.lol
            tls:
            - secretName: cryptpad-tls-ola-lol
              hosts:
                - ola.lol
    - path: manifests/cryptpad
      repoURL: "https://github.com/openlab-aux/k8s"
      targetRevision: main
      directory:
        recurse: true
 