apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directus
spec:
  destination:
    namespace: directus 
    server: "https://kubernetes.default.svc"
  sources:
    - path: manifests/directus
      repoURL: "https://github.com/openlab-aux/k8s"
      targetRevision: main
      directory:
        recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
