apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
spec:
  project: "default"
  destination:
    namespace: loki
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 2.9.11
    chart: loki-stack