apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manyfold
spec:
  destination:
    namespace: manyfold
    server: "https://kubernetes.default.svc"
  sources:
    - chart: redis
<<<<<<< HEAD
      repoURL: https://charts.bitnami.com/bitnami/
=======
      repoURL: "https://charts.bitnami.com/bitnami/"
>>>>>>> k8s/main
      targetRevision: 20.2.1
      helm:
        releaseName: redis
    - path: manifests/manyfold
      repoURL: "https://github.com/openlab-aux/k8s"
      targetRevision: main
      directory:
        recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
