apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 2.17.2
    chart: sealed-secrets
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
