apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
spec:
  project: "default"
  destination:
    namespace: wikijs
    server: "https://kubernetes.default.svc"
  sources:
    - path: manifests/wikijs
      repoURL: "https://github.com/openlab-aux/k8s"
      targetRevision: main
      directory:
        recurse: true
    - repoURL: "https://charts.js.wiki"
      chart: wiki
      targetRevision: 3.0.0
      helm:
        values: |
          postgresql:
            enabled: false
          externalPostgresql:
            username: app
            database: app
            host: db-rw.wikijs.svc.cluster.local
            port: 5432
            existingSecret: db-app
            existingSecretKey: password
          ingress:
            className: nginx
            enabled: true
            hosts:
              - host: wiki.openlab-augsburg.de
                paths:
                  - path: "/"
                    pathType: Prefix
            tls:
              - hosts:
                  - wiki.openlab-augsburg.de
                secretName: wiki.openlab-augsburg.de
