apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xwiki
spec:
  project: "default"
  destination:
    namespace: xwiki
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://xwiki-contrib.github.io/xwiki-helm"
      chart: xwiki
      targetRevision: 1.3.1
      helm:
        values: |
          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: le-staging
            hosts:
            - host: xwiki.lab.weltraumpflege.org
              paths:
                - path: /
                  pathType: Prefix
            tls:
            - secretName: xwiki-tls
              hosts:
                - xwiki.lab.weltraumpflege.org
          mysql:
            enabled: false
          postgresql:
            enabled: true
 