apiVersion: v1
kind: Service
metadata:
  labels:
    app: infopanel2
  name: infopanel2
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 4321
  selector:
    app: infopanel
  type: ClusterIP
