---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: headscale-secrets
  namespace: headscale
spec:
  encryptedData:
    oidcClientId: AgAazNj7SYN1S9ybLws1YRRKaQFHnaxMc2F/v38OGPhF2DhHk/zefxD+CBFN9W0ICBITldnH9eXJEZKmKylJmY/oMpZ21li9+TpwOt5lF6Ie4em/L41CzndT3mUVoEvdzutqXVZg04oaELbJDYIG76xLfKjn4DRcPmnEq3JI8+9LgN5djLX1zgnSyaYwKgAR0O9SJ+AF6t+qF+RMWtRF/2OfNONy6UovS3YhAJnCPghx9D74NZxAfxpWzuNcMZ3ycbs9bUC5I6nNkoulB/FOaX4HGgyraAfD1PIXPrY/4X2ubUc7gx+NG+GHPFIgO8qtpYleVorvgMSj7jhKvxqkDrlA88P51JKPLDabNU4UkQRs1evf43f4DAn+H47myJiGNTnTbfP8Vl27SWuuGsoMvfif9ZXKRXiHOnC7ZsDzanM/J3F1eSI6smPq7QvjOo+z1R/FYMdifBqBXbAA5Y1dJ5Jw4UDlgdILRFX66BXWSQdPHdJIHD77JFmCuOM7bBpCYm+qDoUrg/hYz6FvI5JLc043z1sj6dMW9fNVDnXiOHXaJx5q7Qiw7B5zwbjnTVinErn1aV1HM3zPzGctyC68I8s/hmM+LDovyuatPGoKjTN8sYxa1ylY0/Ht5i41bh0Twg62wUr2T59V8TMziJX75u6Ulsl5gigYxKT+mGzW2zEwOHPcIxur4IBOJ8R2B+fjqqEEMRjzbf+uIeMTSIiJX/FUKQbNpKZQ9+biQqdp5OuTHXLG0FWK3D0/
    oidcClientSecret: AgCF/M2q4IGbrSDYfUz5OkIJqTdRJtvxheEINocgflAPfNs31EZe51ygFffxMuUvODBbFwHbsV4D3cwHEPdHm4RiHWWutAcp9UlND1CCl5CmfAd3AEDhlYQ3LG0JFsPibObdYx85rMBlyGmkeiHl4b4q6Fh8GFCg/47uDyNiv84shxNe4wq7NHu9qwS4UQv+EFeIpvZ3L73PvlcQZuW4PSEIUSwKMhubtsKYU91DdyShCZym8V45dLkoq1zE3sA2A45DLeqDaA0SsjQ05dpYIEuNkYtkRaUHfoI3C5i4W4I+dcmDshGFgbbjwsXlHlGTMmS7y5VCc8QBPTVz1rhnmE9Y4MMxsCa8olRqmnssaETxQpRBt+NxF/lgjVnPqENZeWmP5zb0sVfiE/IECzEsHZtanwLj+GUK9VNeSMKTSfZwUQD1+azA/aGwzVDTlA6BxINy0GvQ25NS/xN+hUeyZIkr/Gc9S7qdbotSn7PsR6GTengiej5adneRhykBy3oTlV85Gd2BdvEtU6NBh29vTDjMM55UDUZVXOo+ni2qGUoR1JIVET7Mka48v2zE5lUuhd6oZULnlRNwypHWscOzOWNr+G7U9IFcftBjqB9UqrQbn+WlNhH7jjphRp7swCU+68EMIoFqp3xGauDNEf/3HgUSKsGSYdjDoaPp5Vy+T9ZnP9o6zuhY5rmPzvjFQb/448dd+2GIEoDcptVWeSUYqklRYuOSsmzpfgHCf0rABITtxku1ui/EO96QHU14oTKhaLgMe7rDq6+ZABdljZFrDQ9C+rBAdUIYwEvR4J0u1LAfJpyKT89q3ENb4/FgmZ6AZqnkIQB561H+SFFtPeGxn/d1M7OwUyoDT6hfuxTNp6JESw==
  template:
    metadata:
      creationTimestamp: null
      name: headscale-secrets
      namespace: headscale
