apiVersion: v1
kind: Service
metadata:
  name: ooye 
  labels:
    app: ooye
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: ooye

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ooye
spec:
  serviceName: ooye
  selector:
    matchLabels:
      app: ooye
  replicas: 1
  template:
    metadata:
      labels:
        app: ooye
    spec:
      containers:
      - name: ooye
        image: sim2kid/ooye-docker:v3.5
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
         - containerPort: 6693
           protocol: TCP
                  commands: ["/bin/tail" "-f" "/dev/null"]

        volumeMounts:
        - name: db
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "openebs-hostpath"
      resources:
        requests:
          storage: 2Gi
